joints:
  - name: Shoulder Pan
    motor_can_id: 1   
    MIT:
        kp: 2.0
        kd: 1.0
    POS_VEL:
        vel_kp: 0.0125
        vel_ki: 0.004
        pos_kp: 150.0
        pos_ki: 0.5
        vlim: 5.0
    posmax: 2.6
    posmin: -2.6
    use_mode: MIT

  - name: Shoulder Lift
    motor_can_id: 2 
    MIT:
        kp: 2.0
        kd: 1.0
    POS_VEL:
        vel_kp: 0.0125
        vel_ki: 0.004
        pos_kp: 150.0
        pos_ki: 0.5
        vlim: 5.0
    posmax: 0
    posmin: -3.8       
    use_mode: MIT

  - name: Elbow Flex
    motor_can_id: 3 
    MIT:
        kp: 2.0
        kd: 1.0
    POS_VEL:
        vel_kp: 0.0125
        vel_ki: 0.004
        pos_kp: 150.0
        pos_ki: 0.5
        vlim: 5.0 
    posmax: 0
    posmin: -3.8
    use_mode: MIT

  - name:  Wrist Flex
    motor_can_id: 4  
    MIT:
        kp: 2.0
        kd: 1.0
    POS_VEL:
        vel_kp: 0.0008
        vel_ki: 0.002
        pos_kp: 50.0
        pos_ki: 1.0
        vlim: 3.0 
    posmax: 1.57
    posmin: -1.57   
    use_mode: MIT

  - name:  Wrist Yaw
    motor_can_id: 5  
    MIT:
        kp: 2.0
        kd: 1.0
    POS_VEL:
        vel_kp: 0.0008
        vel_ki: 0.002
        pos_kp: 50.0
        pos_ki: 1.0
        vlim: 3.0  
    posmax: 1.57
    posmin: -1.57 
    use_mode: MIT


  - name:  Wrist Roll
    motor_can_id: 6  
    MIT:
        kp: 2.0
        kd: 1.0
    POS_VEL:
        vel_kp: 0.0008
        vel_ki: 0.002
        pos_kp: 50.0
        pos_ki: 1.0
        vlim: 3.0   
    posmax: 2.6
    posmin: -2.6
    use_mode: MIT


  - name:  Gripper
    motor_can_id: 7  
    MIT:
        kp: 2.0
        kd: 1.0
    POS_VEL:
        vel_kp: 0.0008
        vel_ki: 0.002
        pos_kp: 50.0
        pos_ki: 1.0
        vlim: 3.0
    posmax: 0
    posmin: -5.2
    use_mode: MIT